/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  ProductCategory,
  UnitType,
  CustomPaymentMethod,
  DiscountScheme,
  DamageReasonOption,
} from '../types/db';

export const DEFAULT_PRODUCT_CATEGORIES: ProductCategory[] = [
  {
    id: 'cat_ceramic',
    name: 'Ceramic Tiles',
    code: 'CERAMIC',
    description: 'Glazed and unglazed kiln-fired ceramic wall and floor tiles',
    color: '#006FEE',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_porcelain',
    name: 'Porcelain Tiles',
    code: 'PORCELAIN',
    description: 'High-density, low-porosity vitrified floor tiles for high-traffic spaces',
    color: '#6366F1',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_vitrified',
    name: 'Vitrified Tiles',
    code: 'VITRIFIED',
    description: 'Ultra-low water absorption polished and glazed vitrified tiles',
    color: '#10B981',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_floor',
    name: 'Floor Tiles',
    code: 'FLOOR',
    description: 'Heavy-duty non-slip residential and commercial floor tiles',
    color: '#F5A524',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_wall',
    name: 'Wall Tiles',
    code: 'WALL',
    description: 'Lightweight interior and exterior architectural wall cladding',
    color: '#7828C8',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_mosaic',
    name: 'Mosaic Tiles',
    code: 'MOSAIC',
    description: 'Mesh-mounted glass, stone, and composite decorative mosaic sheets',
    color: '#06B6D4',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_decor',
    name: 'Decorative Tiles',
    code: 'DECOR',
    description: 'Accent trims, border friezes, and textured feature tiles',
    color: '#E11D48',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_adhesives',
    name: 'Tile Adhesives & Grouts',
    code: 'ADHESIVES',
    description: 'Polymer-modified cementitious tile mortars, epoxies, and joint fillers',
    color: '#0D9488',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_trims',
    name: 'Trims & Profiles',
    code: 'TRIMS',
    description: 'Aluminum, PVC, and stainless steel edge protection profiles',
    color: '#EA580C',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_sanitary',
    name: 'Sanitary & Fixtures',
    code: 'SANITARY',
    description: 'Bathroom fixtures, faucets, valves, and plumbing accessories',
    color: '#475569',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_UNIT_TYPES: UnitType[] = [
  {
    id: 'unit_box',
    name: 'Carton (Box)',
    abbreviation: 'box',
    description: 'Standard packaged box/carton of tiles',
    allowDecimals: false,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'unit_pc',
    name: 'Piece (Tile)',
    abbreviation: 'pc',
    description: 'Single tile unit or individual piece',
    allowDecimals: false,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'unit_sqm',
    name: 'Square Meter (sqm)',
    abbreviation: 'sqm',
    description: 'Area measurement for surface coverage',
    allowDecimals: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'unit_bag',
    name: 'Bag / Sack',
    abbreviation: 'bag',
    description: 'Cement, tile adhesive, or dry chemical compound sack (20kg/25kg)',
    allowDecimals: false,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'unit_m',
    name: 'Linear Meter',
    abbreviation: 'm',
    description: 'Linear length for aluminum trims and edging strips',
    allowDecimals: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'unit_roll',
    name: 'Roll',
    abbreviation: 'roll',
    description: 'Waterproofing membrane or isolation sheet roll',
    allowDecimals: false,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'unit_set',
    name: 'Set / Kit',
    abbreviation: 'set',
    description: 'Multi-part complete installation kit or sanitary fixture set',
    allowDecimals: false,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_PAYMENT_METHODS: CustomPaymentMethod[] = [
  {
    id: 'pm_cash',
    name: 'Cash',
    code: 'CASH',
    category: 'Cash',
    requiresReference: false,
    color: 'border-emerald-500/25 text-emerald-600 dark:text-emerald-400 bg-emerald-500/5',
    activeColor: 'bg-emerald-600 border-emerald-600 text-white',
    instructions: 'Standard physical cash drawer settlement',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pm_gcash',
    name: 'GCash',
    code: 'GCASH',
    category: 'E-Wallet',
    requiresReference: true,
    referenceLabel: '13-Digit GCash Reference No.',
    color: 'border-sky-500/25 text-sky-600 dark:text-sky-400 bg-sky-500/5',
    activeColor: 'bg-sky-600 border-sky-600 text-white',
    instructions: 'Scan Store GCash QR code or transfer to registered store wallet',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pm_maya',
    name: 'Maya',
    code: 'MAYA',
    category: 'E-Wallet',
    requiresReference: true,
    referenceLabel: 'Maya Reference / Txn ID',
    color: 'border-green-500/25 text-green-600 dark:text-green-400 bg-green-500/5',
    activeColor: 'bg-green-600 border-green-600 text-white',
    instructions: 'Scan Maya QR Ph code or pay via merchant number',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pm_card',
    name: 'Card / Bank Terminal',
    code: 'CARD',
    category: 'Card',
    requiresReference: true,
    referenceLabel: 'POS Terminal Approval / Auth Code',
    color: 'border-violet-500/25 text-violet-600 dark:text-violet-400 bg-violet-500/5',
    activeColor: 'bg-violet-600 border-violet-600 text-white',
    instructions: 'Swipe, insert, or tap Credit/Debit card on physical payment terminal',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pm_credit',
    name: 'Member Credit',
    code: 'CREDIT',
    category: 'Credit',
    requiresReference: false,
    color: 'border-primary/25 text-primary bg-primary/5',
    activeColor: 'bg-primary border-primary text-white',
    instructions: 'Charge to VIP Account or approved contractor revolving credit line',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pm_bank_transfer',
    name: 'Bank Transfer / InstaPay',
    code: 'BANK_TRANSFER',
    category: 'Bank',
    requiresReference: true,
    referenceLabel: 'Bank Transfer / Trace No.',
    color: 'border-amber-500/25 text-amber-600 dark:text-amber-400 bg-amber-500/5',
    activeColor: 'bg-amber-600 border-amber-600 text-white',
    instructions: 'Direct bank deposit or InstaPay / PESONet wire confirmation',
    isEnabled: true,
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pm_check',
    name: 'Check Payment',
    code: 'CHECK',
    category: 'Other',
    requiresReference: true,
    referenceLabel: 'Check Number & Bank Branch',
    color: 'border-indigo-500/25 text-indigo-600 dark:text-indigo-400 bg-indigo-500/5',
    activeColor: 'bg-indigo-600 border-indigo-600 text-white',
    instructions: 'Corporate check clearing (requires supervisor ID authorization)',
    isEnabled: true,
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_DISCOUNT_SCHEMES: DiscountScheme[] = [
  {
    id: 'disc_senior',
    name: 'Senior Citizen',
    code: 'SENIOR',
    type: 'PERCENT',
    value: 20,
    vatExempt: true,
    requiresIdNumber: true,
    requiresCustomerName: true,
    description: '20% Off base price + 12% VAT exemption (Philippine RA 9994).',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'disc_pwd',
    name: 'PWD Resident',
    code: 'PWD',
    type: 'PERCENT',
    value: 20,
    vatExempt: true,
    requiresIdNumber: true,
    requiresCustomerName: true,
    description: '20% Off base price + 12% VAT exemption (Philippine RA 10754).',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'disc_contract',
    name: 'Contractor Alliance',
    code: 'CONTRACT',
    type: 'PERCENT',
    value: 10,
    vatExempt: false,
    requiresIdNumber: false,
    requiresCustomerName: true,
    description: 'Flat 10% Trade Allied partner volume discount.',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'disc_wholesale',
    name: 'Wholesale Tier',
    code: 'WHOLESALE',
    type: 'PERCENT',
    value: 15,
    vatExempt: false,
    requiresIdNumber: false,
    requiresCustomerName: false,
    minimumSpend: 50000,
    description: '15% Volume discount for orders reaching ₱50,000 or above.',
    isEnabled: true,
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'disc_promo_500',
    name: 'Store Voucher ₱500',
    code: 'PROMO_500',
    type: 'FLAT',
    value: 500,
    vatExempt: false,
    requiresIdNumber: false,
    requiresCustomerName: false,
    minimumSpend: 5000,
    description: '₱500 Flat Store Voucher on qualifying carts of ₱5,000+.',
    isEnabled: true,
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_DAMAGE_REASONS: DamageReasonOption[] = [
  {
    id: 'dmg_wh_break',
    name: 'Warehouse Breakage / Stacking Collapse',
    code: 'WH_BREAK',
    category: 'Warehouse Breakage',
    defaultAction: 'Disposed / Scrapped',
    description: 'Warehouse drop, pallet tipping, or forklift impact fracture',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'dmg_boa',
    name: 'Broken On Arrival (BOA)',
    code: 'BOA',
    category: 'BOA',
    defaultAction: 'Returned to Supplier',
    description: 'Broken materials found inside sealed manufacturer carton upon arrival',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'dmg_showroom',
    name: 'Showroom Casualty',
    code: 'SHOWROOM',
    category: 'Showroom Casualty',
    defaultAction: 'Discounted Clearance',
    description: 'Display racks chipped, corner fractures during customer inspection',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'dmg_transit',
    name: 'Delivery Transit Fractures',
    code: 'TRANSIT',
    category: 'Delivery Transit',
    defaultAction: 'Disposed / Scrapped',
    description: 'Fractures occurring during dispatch or truck transport to customer site',
    isEnabled: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'dmg_expired',
    name: 'Expired / Hardened Chemical Batch',
    code: 'EXPIRED',
    category: 'Warehouse Breakage',
    defaultAction: 'Disposed / Scrapped',
    description: 'Tile adhesive, epoxy, or grout cured beyond shelf expiration period',
    isEnabled: true,
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
];
